# Generated by Django 3.2.3 on 2022-12-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopizza', models.CharField(blank=True, max_length=20, null=True)),
                ('tamano', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
